# Generated by Django 4.2.7 on 2023-12-04 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMV', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Irradiated_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IR', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Irradiated_Products',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_Number', models.CharField(max_length=10)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='Cryo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Cryo_Measurement',
            field=models.CharField(choices=[('Units', 'Units'), ('Ml', 'Ml')], default='Units', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Cryo_Quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='DAT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Date_Submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='FFP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='FFP_Measurement',
            field=models.CharField(choices=[('Units', 'Units'), ('Ml', 'Ml')], default='Units', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='FFP_Quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='GS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='High_Risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Neither',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Other_CMV',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Other_IR',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Other_Test',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Platelets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Platelets_Measurement',
            field=models.CharField(choices=[('Units', 'Units'), ('Ml', 'Ml')], default='Units', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Platelets_Quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='RC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='RC_Measurement',
            field=models.CharField(choices=[('Units', 'Units'), ('Ml', 'Ml')], default='Units', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='RC_Quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Recent_Transfusion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupation', models.CharField(choices=[('Consultant', 'Consultant'), ('GP', 'GP'), ('Doctor', 'Doctor'), ('Other', 'Other')], default='Consultant', max_length=10)),
                ('Extension', models.CharField(max_length=10)),
                ('Fullname', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='CMV',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestforms.cmv'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='IR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestforms.irradiated_products'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestforms.user'),
        ),
    ]
