# Generated by Django 4.2.7 on 2023-12-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0002_cmv_irradiated_products_patient_transaction_cryo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='System_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requestforms.patient'),
        ),
    ]
