# Generated by Django 4.2.7 on 2023-12-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0003_transaction_system_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Neither',
        ),
    ]
