# Generated by Django 4.2.7 on 2023-12-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0004_remove_transaction_neither'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CMV',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CMV',
        ),
    ]
