# Generated by Django 4.2.7 on 2023-12-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0005_alter_transaction_cmv_delete_cmv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='IR',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Irradiated_Products',
        ),
    ]
