# Generated by Django 4.2.7 on 2023-12-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0006_alter_transaction_ir_delete_irradiated_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Other_CMV',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Other_IR',
        ),
    ]
